version: '3'

services:
  nginx-rtmp:
    build: .
    ports:
      - 1935:1935
      - 8080:80
      - 8443:443
    environment:
      - HTTP_PORT=80
      - RTMP_PORT=1935
      - STREAM_PUBLISH_NOTIFY_URL=http://127.0.0.1/push/notify
      - RTMP_TRANSCODE_IP=127.0.0.1
      - RTMP_HLS_IP=127.0.0.1
    volumes:
      - ./certs:/opt/certs
      - ./conf.d:/opt/conf.d